# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [6]:
import pandas as pd
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep='\t')

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [7]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [24]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]))

TypeError: 'float' object is not subscriptable

In [25]:
chipo[chipo['item_price'] > 10.00].shape[0]

1130

In [29]:
chipo_copy = chipo.copy()
chipo_copy['product_price'] = chipo_copy['item_price'] / chipo_copy['quantity']
chipo_copy = chipo_copy.drop_duplicates(['item_name','choice_description'])
chipo_copy = chipo_copy.loc[chipo_copy['product_price'] > 10.00, ['item_name','choice_description', 'product_price']].reset_index(drop=True)
chipo_copy

,item_name,choice_description,product_price
0,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
4,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...
702,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
703,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
704,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
705,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
706,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [31]:
chipo_copy[['item_name','choice_description', 'product_price']]

,item_name,choice_description,product_price
0,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
2,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
4,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...
702,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
703,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
704,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
705,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
706,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

### Step 6. Sort by the name of the item

In [32]:
chipo_copy[['item_name','choice_description', 'product_price']].sort_values('item_name')

,item_name,choice_description,product_price
478,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.75
481,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75
636,Barbacoa Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",11.75
589,Barbacoa Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",11.75
156,Barbacoa Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
...,...,...,...
93,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
36,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
644,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
125,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
304,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25

### Step 7. What was the quantity of the most expensive item ordered?

In [47]:
chipo.loc[chipo["item_price"].idxmax()]["quantity"]

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [51]:
chipo.loc[chipo["item_name"] == "Veggie Salad Bowl"]['quantity'].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [55]:
chipo['test'] = chipo.loc[chipo["item_name"] == "Canned Soda"]['quantity']

In [ ]:
(
    chipo[
        (chipo["item_name"] == "Canned Soda") &
        (chipo["quantity"] > 1)
    ]
    .shape[0]
)

20